# Generated by Django 4.1.3 on 2022-12-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='address',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='phonenumber',
            new_name='transactionId',
        ),
    ]
