# Generated by Django 4.1.3 on 2022-12-02 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_address_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(max_length=200)),
                ('balance', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='transactionObject',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
