# Generated by Django 4.1.3 on 2022-12-03 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_account_rename_user_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='AccountID',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionId',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionObject',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionType',
            new_name='ReceivingAccountID',
        ),
        migrations.AddField(
            model_name='transaction',
            name='TransactionAmount',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='TransactionId',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
